apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-system
  name: ocsp-response-updater
  labels:
    app: ocsp-poc
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "list"]
