kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: ocsp-response-updater-rb
  labels:
    app: ocsp-poc
subjects:
- kind: ServiceAccount
  name: ocsp-response-updater-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: Role
  name: ocsp-response-updater
  apiGroup: rbac.authorization.k8s.io